asdfasdfas[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"asdfasdf

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
